include(${CMAKE_CURRENT_LIST_DIR}/interfaces/mc_mujoco.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/interfaces/kinova_mj_description.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_adc_collision_sensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_ros_imu_sensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_ros_force_sensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_energy_residual.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_energy_residual_current.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_energy_residual_torque.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_current_residual.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_torque_residual.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_detection_zurlo.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_detection_momentum_error.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_detection_pi_sliding.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_detection_force_torque_sensor.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_collision_detection_jerk.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/plugins/mc_super_twisting.cmake)
include(${CMAKE_CURRENT_LIST_DIR}/controllers/collision_benchmark_controller.cmake)

